### ISSUE TITLE
Unable to set 12 a.m. as 12 instead of 0.

### ISSUE THREAD

**Issue by ericjgruber** [eimihar/myjqdatepicker#1]
I am using this in a project, and it works pretty well. However, I am unable to choose 12 a.m. and have it display as 12:00. Rather, it displays as 0:00. So, if I select something like 12:16 AM, it shows as 0:16 AM. 

Is there a simple way to change it so that it shows the hour selected as stated above? Thanks!

**Comment by eimihar** [comment]
Hi, thanks for using this very old plugin ^^'. glad you find it working.

I can patch it out but it would require moment.js if it's okay with you.
the usage would be something like :
```
$('#date_input').mydatepicker(2, {format: 'hh:mm A'})
```

will this be okay with you?

**Comment by ericjgruber** [comment]
Yes. Sounds like a good plan if you are interested in updating it.

**Comment by eimihar** [comment]
Alright, i pushed the update.

You can do something like : 
```$('#date_input').mydatepicker(2, {format: 'hh:mm A'})```

But first you need to require moment.js. 

More about the format can be found at momentjs website itself. Thanks!

**Comment by ericjgruber** [comment]
Thank you!

**Comment by ericjgruber** [comment]
This worked great! Thanks for the update.

If you get a chance, shoot me an email at my github username at gmail. I want to tell you about how this library is being used.
